---
- id: version-badge
  name: Generate a badge with the Grid version
  description: >
    Open the copier answers file to grab the Grid template version.
  entry: grid-version-badge
  language: python
  pass_filenames: false
  always_run: true
- id: comment-dependencies
  name: Add comments with team names for `depends_on` blocks
  entry: comment-dependencies
  language: python
  pass_filenames: true
  files: "dp-*/dp_*/configs/*.ya?ml"
